title: Michelle Ho
email: michelle.y.ho@gmail.com
description: Software Engineer - Python
favicon: true
theme: jekyll-theme-minimal


platforms:
  - name: GitHub
    icon: <i class="fa-brands fa-github"></i>
    link: https://github.com/michelleyho
  - name: LinkedIn
    icon: <i class="fa-brands fa-linkedin"></i>
    link: https://www.linkedin.com/in/michelle-ho-0999161a
  - name: Résumé
    icon: <i class="fa-solid fa-file-lines"></i>
    link: ./assets/resumes/july_2024.pdf
